name: Learning Github Action
on: [push]
jobs:
  docker-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: guganabu/github-action@main
        id: checkout-repo
        with:
          who-to-greet: 'Gugan Abu'
          app_path: '/var/www/html'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.checkout-repo.outputs.time }} and path ${{ steps.checkout-repo.outputs.path }}"
